#!/usr/bin/env python3
"""Regenerate journal/YYYY-MM.md and INDEX.md from models/*.yaml.

Generated files carry a header line so contributors know not to edit them
by hand. Run after any model YAML change; CI checks the working tree is
clean.
"""

from __future__ import annotations

import datetime as dt
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("error: pyyaml not installed. Run: pip install pyyaml jsonschema")


ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = ROOT / "models"
JOURNAL_DIR = ROOT / "journal"
INDEX_PATH = ROOT / "INDEX.md"

GENERATED_HEADER = (
    "<!-- generated by scripts/build.py from models/*.yaml — do not edit -->\n\n"
)


def load_entries() -> list[dict[str, Any]]:
    entries = []
    for path in sorted(MODELS_DIR.glob("*.yaml")):
        if path.name == "TEMPLATE.yaml":
            continue
        data = yaml.safe_load(path.read_text())
        entries.append(data)
    return entries


def as_date(value: Any) -> dt.date:
    if isinstance(value, dt.date):
        return value
    return dt.date.fromisoformat(str(value))


def fmt_context(v: Any) -> str:
    if v is None:
        return "—"
    n = int(v)
    if n >= 1_000_000 and n % 1_000_000 == 0:
        return f"{n // 1_000_000}M"
    if n >= 1_000 and n % 1_000 == 0:
        return f"{n // 1_000}K"
    return str(n)


def fmt_modalities(mods: Any) -> str:
    if not mods:
        return "—"
    return ", ".join(mods)


def fmt_sources(sources: Any) -> str:
    if not sources:
        return "—"
    return " ".join(f"[src]({u})" for u in sources)


def render_journal_month(month: str, entries: list[dict[str, Any]]) -> str:
    year, mon = month.split("-")
    month_name = dt.date(int(year), int(mon), 1).strftime("%B %Y")
    lines = [GENERATED_HEADER.rstrip(), "", f"# {month_name}", ""]
    lines.append("| Date | Model | Provider | Context | Modalities | Status | Sources |")
    lines.append("|------|-------|----------|---------|------------|--------|---------|")
    for e in entries:
        lines.append(
            "| {date} | [{name}](../models/{mid}.yaml) | {provider} | {ctx} | {mods} | {status} | {srcs} |".format(
                date=e["release_date"],
                name=e.get("display_name") or e["model_id"],
                mid=e["model_id"],
                provider=e.get("provider", "—"),
                ctx=fmt_context(e.get("context_window")),
                mods=fmt_modalities(e.get("modalities")),
                status=e.get("status", "stable"),
                srcs=fmt_sources(e.get("sources")),
            )
        )
    lines.append("")
    for e in entries:
        lines.append(f"### {e.get('display_name') or e['model_id']}")
        lines.append("")
        lines.append(f"- **model_id:** `{e['model_id']}`")
        lines.append(f"- **provider:** {e.get('provider', '—')}")
        lines.append(f"- **release_date:** {e['release_date']}")
        lines.append(f"- **context_window:** {fmt_context(e.get('context_window'))}")
        lines.append(f"- **modalities:** {fmt_modalities(e.get('modalities'))}")
        lines.append(f"- **status:** {e.get('status', 'stable')}")
        if e.get("supersedes"):
            lines.append(f"- **supersedes:** `{e['supersedes']}`")
        if e.get("sources"):
            lines.append(f"- **sources:** {fmt_sources(e['sources'])}")
        notes = (e.get("notes") or "").strip()
        if notes:
            lines.append("")
            lines.append(notes)
        lines.append("")
    return "\n".join(lines) + "\n"


def render_index(entries: list[dict[str, Any]]) -> str:
    by_date = sorted(
        entries, key=lambda e: (as_date(e["release_date"]), e["model_id"]), reverse=True
    )
    lines = [GENERATED_HEADER.rstrip(), "", "# Model Release Index", ""]
    lines.append(f"{len(entries)} entries.")
    lines.append("")
    lines.append("| Date | Model | Provider | Context | Modalities | Status |")
    lines.append("|------|-------|----------|---------|------------|--------|")
    for e in by_date:
        lines.append(
            "| {date} | [{name}](models/{mid}.yaml) | {provider} | {ctx} | {mods} | {status} |".format(
                date=e["release_date"],
                name=e.get("display_name") or e["model_id"],
                mid=e["model_id"],
                provider=e.get("provider", "—"),
                ctx=fmt_context(e.get("context_window")),
                mods=fmt_modalities(e.get("modalities")),
                status=e.get("status", "stable"),
            )
        )
    lines.append("")
    lines.append("## By provider")
    lines.append("")
    by_provider: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for e in entries:
        by_provider[e.get("provider", "Unknown")].append(e)
    for provider in sorted(by_provider):
        lines.append(f"### {provider}")
        lines.append("")
        for e in sorted(by_provider[provider], key=lambda e: as_date(e["release_date"]), reverse=True):
            lines.append(
                f"- `{e['model_id']}` — {e.get('display_name') or e['model_id']} ({e['release_date']})"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    entries = load_entries()
    if not entries:
        sys.exit("no entries under models/")

    by_month: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for e in entries:
        d = as_date(e["release_date"])
        by_month[f"{d.year:04d}-{d.month:02d}"].append(e)

    JOURNAL_DIR.mkdir(exist_ok=True)
    existing = {p.name for p in JOURNAL_DIR.glob("*.md")}
    written = set()
    for month, es in by_month.items():
        es_sorted = sorted(es, key=lambda e: (as_date(e["release_date"]), e["model_id"]), reverse=True)
        path = JOURNAL_DIR / f"{month}.md"
        path.write_text(render_journal_month(month, es_sorted))
        written.add(path.name)
        print(f"wrote {path.relative_to(ROOT)}")

    # Remove stale generated journal files (ones that no longer have entries).
    for name in existing - written:
        stale = JOURNAL_DIR / name
        text = stale.read_text()
        if text.startswith(GENERATED_HEADER.rstrip()):
            stale.unlink()
            print(f"removed {stale.relative_to(ROOT)} (no entries)")

    INDEX_PATH.write_text(render_index(entries))
    print(f"wrote {INDEX_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
